---
  time_intervals:
    send_heroes_for_work: 30 #min
    coin_check: 20 #min
    interval_between_moviments: 1 #s

  # how confident the bot needs to be to click the button 0-1
  trashhold:
    default: 0.7
    commom: 0.8
    select_wallet_buttons: 0.8
    go_to_work_btn: 0.9

  scroll_size: 60
  use_click_and_drag_instead_of_scroll: true
  
